# Generated by Django 6.0.3 on 2026-03-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.CharField(blank=True, null=True)),
                ('lng', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
