# Generated by Django 6.0.3 on 2026-03-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
