# Generated by Django 6.0.3 on 2026-03-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
