# Generated by Django 6.0.3 on 2026-03-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_address_location_created_at_and_more'),
        ('member', '0004_member_created_at_member_phone_member_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
